Allowing the spy names to be more descriptive
This changes the error from

    AssertError: expected spy, spy, spy to be called in order but were called as spy, spy, spy

to a far more useful

    AssertError: expected handler1, handler2, handler3 to be called in order but were called as handler1, handler3, handler2